### ISSUE TITLE
Login error mysql 

### ISSUE THREAD

**Issue by makitv** [hudolejev/agama#3]
After completing lab 4 task 7 and trying to login to mysql using command "mysql -u agama -p" i get error

![task7 error](https://user-images.githubusercontent.com/55987746/96473218-09fe5c80-123a-11eb-8ad3-ffb9e4b9f8b6.png)

This is the task file where i make my sql user and also db

![task_file_to_make_user_and_db](https://user-images.githubusercontent.com/55987746/96473505-66fa1280-123a-11eb-98bf-38e4320e7363.PNG)

**Comment by hudolejev** [comment]
This probably belongs to https://github.com/romankuchin/ica0002-2020 and has nothing to do with this app. Please re-open this issue in the correct repository.

The error you're getting says that you are using the wrong username/password combination.
